# Generated by Django 4.0.6 on 2022-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.CharField(default='00.00', max_length=30),
        ),
        migrations.AddField(
            model_name='menubar',
            name='price',
            field=models.CharField(default='00.00', max_length=30),
        ),
    ]
